### ISSUE TITLE
cgroup2: check list for v2 controller implementations

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/cgroups#104]
## Urgent (required to get CRI and Moby work)
- [x] pids: #103
- [x] cpu: #107
- [x] memory (`memory.stats`): #108 @Zyqsempai
- [x] `memory.current`, `memory.swap.current`, and other memory stat files  https://www.kernel.org/doc/Documentation/cgroup-v2.txt : #117 
- [x] OOM event FD: #115
- [x] io: #112
- [x] devices (BPF): #116
- [x] `ToggleControllers()` (issue: https://github.com/containerd/cgroups/issues/121): #124

Metrics functions are urgent.
`Update()` functions are not necessary for CRI and Moby.

## Non-urgent
- [x] `NewSystemd()` and `LoadSystemd()`: #125 
- [x] freezer: #103
- [ ] perf_event
- [x] cpuset: #111
- [x] rdma: #119 
- [x] [hugetlb](https://www.spinics.net/lists/cgroups/msg24003.html) (to appear in kernel 5.XX)

**Comment by Zyqsempai** [comment]
@AkihiroSuda Can I help you somehow on this one?

**Comment by AkihiroSuda** [comment]
thanks, which do you plan to work on?

**Comment by Zyqsempai** [comment]
@AkihiroSuda I will take memory part if you don't mind.

**Comment by AkihiroSuda** [comment]
thanks, please open PR when #103 gets merged

**Comment by AkihiroSuda** [comment]
#103 merged

**Comment by Zyqsempai** [comment]
@crosbymichael So what do you have in plans? Should I open PR with the next part(memory) ? add then we will add a manager above it?

**Comment by crosbymichael** [comment]
@Zyqsempai sure, go ahead and open more if you still have more coming.

Thanks!

**Comment by Zyqsempai** [comment]
Guys, I will also take the rest if you don't mind!

**Comment by Zyqsempai** [comment]
So guys, let's summarize what we still have to do here?

**Comment by crosbymichael** [comment]
We need OOM notifications from the memory controller as well as the bpf devices code added to this repo

**Comment by AkihiroSuda** [comment]
Do we need devices controller for CRI and Moby?

**Comment by Zyqsempai** [comment]
@crosbymichael @AkihiroSuda I will take OOM notifications and bpf devices.

**Comment by crosbymichael** [comment]
@AkihiroSuda i don't want to put out any cgroups code without device support as it's very important to security

**Comment by Zyqsempai** [comment]
@AkihiroSuda For `bpf` implementation, can i rely on your `bpf` implementation for `runc`? 
https://github.com/opencontainers/runc/tree/master/libcontainer/cgroups/ebpf

**Comment by AkihiroSuda** [comment]
Yes, please

**Comment by Zyqsempai** [comment]
@AkihiroSuda @crosbymichael Which memory stats should we add?
`memory.current`, `memory.max`, `memory.swap.current`, `memory.swap.max` will be enough?

**Comment by AkihiroSuda** [comment]
yes

**Comment by Zyqsempai** [comment]
Good, then i will take it.

**Comment by Zyqsempai** [comment]
Hey guys, In next PR's i will work on `perf_event` and `rdma`
